package lt.psk.tools.mybatis.model;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.ID
     *
     * @mbg.generated Mon May 02 20:32:15 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Mon May 02 20:32:15 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.OCCUPATION
     *
     * @mbg.generated Mon May 02 20:32:15 EEST 2022
     */
    private String occupation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.ID
     *
     * @return the value of PUBLIC.CLIENT.ID
     *
     * @mbg.generated Mon May 02 20:32:15 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.ID
     *
     * @param id the value for PUBLIC.CLIENT.ID
     *
     * @mbg.generated Mon May 02 20:32:15 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.NAME
     *
     * @return the value of PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Mon May 02 20:32:15 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.NAME
     *
     * @param name the value for PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Mon May 02 20:32:15 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.OCCUPATION
     *
     * @return the value of PUBLIC.CLIENT.OCCUPATION
     *
     * @mbg.generated Mon May 02 20:32:15 EEST 2022
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.OCCUPATION
     *
     * @param occupation the value for PUBLIC.CLIENT.OCCUPATION
     *
     * @mbg.generated Mon May 02 20:32:15 EEST 2022
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
}