package lt.psk.tools.mybatis.model;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.ID
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.ADDRESS
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.CITY
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.ID
     *
     * @return the value of PUBLIC.SHOP.ID
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.ID
     *
     * @param id the value for PUBLIC.SHOP.ID
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.ADDRESS
     *
     * @return the value of PUBLIC.SHOP.ADDRESS
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.ADDRESS
     *
     * @param address the value for PUBLIC.SHOP.ADDRESS
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.CITY
     *
     * @return the value of PUBLIC.SHOP.CITY
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.CITY
     *
     * @param city the value for PUBLIC.SHOP.CITY
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public void setCity(String city) {
        this.city = city;
    }
}