package lt.psk.tools.mybatis.model;

public class Tool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOOL.ID
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOOL.BRAND
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOOL.CATEGORY
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOOL.TOOL_NAME
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    private String toolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TOOL.SHOPS_ID
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    private Long shopsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOOL.ID
     *
     * @return the value of PUBLIC.TOOL.ID
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOOL.ID
     *
     * @param id the value for PUBLIC.TOOL.ID
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOOL.BRAND
     *
     * @return the value of PUBLIC.TOOL.BRAND
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOOL.BRAND
     *
     * @param brand the value for PUBLIC.TOOL.BRAND
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOOL.CATEGORY
     *
     * @return the value of PUBLIC.TOOL.CATEGORY
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOOL.CATEGORY
     *
     * @param category the value for PUBLIC.TOOL.CATEGORY
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOOL.TOOL_NAME
     *
     * @return the value of PUBLIC.TOOL.TOOL_NAME
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public String getToolName() {
        return toolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOOL.TOOL_NAME
     *
     * @param toolName the value for PUBLIC.TOOL.TOOL_NAME
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public void setToolName(String toolName) {
        this.toolName = toolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TOOL.SHOPS_ID
     *
     * @return the value of PUBLIC.TOOL.SHOPS_ID
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public Long getShopsId() {
        return shopsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TOOL.SHOPS_ID
     *
     * @param shopsId the value for PUBLIC.TOOL.SHOPS_ID
     *
     * @mbg.generated Mon May 02 20:27:54 EEST 2022
     */
    public void setShopsId(Long shopsId) {
        this.shopsId = shopsId;
    }
}